### ISSUE TITLE
How is prettier used in this repo?

### ISSUE THREAD

**Issue by motomic-efdezpolo** [ansidev/astro-basic-template#406]
Hello there!

Nice template! I've discovered new cool tools!

I have a question, how is prettier used? I do not get what impact has the config.

**Comment by ansidev** [comment]
Hi @motomic-efdezpolo!

I'm not sure what you mean, prettier is a common code formatter.

If you are not familiar with prettier, I suggest you to read their [documentation](https://prettier.io/docs/en/) first to understand how it works.

**Comment by motomic-efdezpolo** [comment]
I mean if I remove prettier deps and config nothing seems to happen. Where is prettier called?

**Comment by ansidev** [comment]
@motomic-efdezpolo
1. I am using Visual Studio Code and `prettier` is called by [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode).
2. You can call it using [CLI](https://prettier.io/docs/en/cli), I just not add the script for quick calling.

**Comment by motomic-efdezpolo** [comment]
Ok now it makes sense! I thought it was integrated somehow in a husky hook or task.

Thanks!
